with open('templates/show_form_edit.html', 'r', encoding='utf-8') as f:
    lines = f.readlines()

new_block = (
    '  {% set photos_count = (1 if show.file_name else 0) + (1 if show.file_name2 else 0) + (1 if show.file_name3 else 0) %}\n'
    '  {% if show.file_name and show.is_pdf() %}\n'
    '    <p>Fichier actuel :\n'
    '        <a href="{{ url_for(\'uploaded_file\', filename=show.file_name) }}" target="_blank">\n'
    '            \U0001f4c4 Voir le PDF ({{ show.file_name }})\n'
    '        </a>\n'
    '    </p>\n'
    '  {% elif photos_count > 0 %}\n'
    '    <div style="background:{% if photos_count >= 2 %}linear-gradient(135deg, #27ae60 0%, #2ecc71 100%){% else %}linear-gradient(135deg, #e74c3c 0%, #c0392b 100%){% endif %}; padding:12px 16px; border-radius:10px; margin-bottom:16px; box-shadow:0 4px 12px rgba(0,0,0,0.15);">\n'
    '      <div style="display:flex; align-items:center; gap:12px;">\n'
    '        <span style="font-size:2rem;">{% if photos_count >= 2 %}\u2705{% else %}\u26a0\ufe0f{% endif %}</span>\n'
    '        <div style="flex:1;">\n'
    '          <strong style="color:#fff; display:block; font-size:1rem; margin-bottom:4px;">{{ photos_count }}/2 photos minimum</strong>\n'
    '          <span style="color:#fff; font-size:0.85rem; opacity:0.95;">\n'
    '            {% if photos_count >= 2 %}\n'
    '              Votre spectacle a suffisamment de photos pour \u00eatre publi\u00e9\u00a0!\n'
    '            {% else %}\n'
    '              {% set manquantes = 2 - photos_count %}\n'
    '              Il manque encore {{ manquantes }} photo{% if manquantes > 1 %}s{% endif %} pour pouvoir publier ce spectacle.\n'
    '            {% endif %}\n'
    '          </span>\n'
    '        </div>\n'
    '      </div>\n'
    '    </div>\n'
    '    <p>Photos actuelles\u00a0:</p>\n'
    '    <div style="display:grid; grid-template-columns:repeat(3, 1fr); gap:12px; margin-bottom:16px;">\n'
    '      {% if show.has_image() %}\n'
    '      <div style="text-align:center; position:relative;">\n'
    '        <span style="font-size:0.85rem; color:var(--muted); display:block; margin-bottom:6px;">Photo 1 (principale)</span>\n'
    '        <img src="{{ url_for(\'uploaded_file\', filename=show.file_name) }}" alt="{{ show.title }}" style="max-width:100%; max-height:150px; border-radius:6px; border:1px solid var(--border);">\n'
    '        <button type="button" onclick="deletePhoto({{ show.id }}, \'file_name\')" style="position:absolute; top:28px; right:8px; background:#ef4444; color:white; border:none; padding:6px 10px; border-radius:6px; cursor:pointer; font-size:0.85rem;" title="Supprimer cette photo">\U0001f5d1\ufe0f Supprimer</button>\n'
    '      </div>\n'
    '      {% else %}\n'
    '      <div style="text-align:center; opacity:0.5;">\n'
    '        <span style="font-size:0.85rem; color:var(--muted); display:block; margin-bottom:6px;">Photo 1 (principale)</span>\n'
    '        <div style="height:100px; background:var(--bg); border-radius:6px; border:1px dashed var(--border); display:flex; align-items:center; justify-content:center; color:var(--muted);">Non d\u00e9finie</div>\n'
    '      </div>\n'
    '      {% endif %}\n'
    '      {% if show.has_image2() %}\n'
    '      <div style="text-align:center; position:relative;">\n'
    '        <span style="font-size:0.85rem; color:var(--muted); display:block; margin-bottom:6px;">Photo 2</span>\n'
    '        <img src="{{ url_for(\'uploaded_file\', filename=show.file_name2) }}" alt="{{ show.title }} - Photo 2" style="max-width:100%; max-height:150px; border-radius:6px; border:1px solid var(--border);">\n'
    '        <button type="button" onclick="deletePhoto({{ show.id }}, \'file_name2\')" style="position:absolute; top:28px; right:8px; background:#ef4444; color:white; border:none; padding:6px 10px; border-radius:6px; cursor:pointer; font-size:0.85rem;" title="Supprimer cette photo">\U0001f5d1\ufe0f Supprimer</button>\n'
    '      </div>\n'
    '      {% else %}\n'
    '      <div style="text-align:center; opacity:0.5;">\n'
    '        <span style="font-size:0.85rem; color:var(--muted); display:block; margin-bottom:6px;">Photo 2</span>\n'
    '        <div style="height:100px; background:var(--bg); border-radius:6px; border:1px dashed var(--border); display:flex; align-items:center; justify-content:center; color:var(--muted);">Non d\u00e9finie</div>\n'
    '      </div>\n'
    '      {% endif %}\n'
    '      {% if show.has_image3() %}\n'
    '      <div style="text-align:center; position:relative;">\n'
    '        <span style="font-size:0.85rem; color:var(--muted); display:block; margin-bottom:6px;">Photo 3</span>\n'
    '        <img src="{{ url_for(\'uploaded_file\', filename=show.file_name3) }}" alt="{{ show.title }} - Photo 3" style="max-width:100%; max-height:150px; border-radius:6px; border:1px solid var(--border);">\n'
    '        <button type="button" onclick="deletePhoto({{ show.id }}, \'file_name3\')" style="position:absolute; top:28px; right:8px; background:#ef4444; color:white; border:none; padding:6px 10px; border-radius:6px; cursor:pointer; font-size:0.85rem;" title="Supprimer cette photo">\U0001f5d1\ufe0f Supprimer</button>\n'
    '      </div>\n'
    '      {% else %}\n'
    '      <div style="text-align:center; opacity:0.5;">\n'
    '        <span style="font-size:0.85rem; color:var(--muted); display:block; margin-bottom:6px;">Photo 3</span>\n'
    '        <div style="height:100px; background:var(--bg); border-radius:6px; border:1px dashed var(--border); display:flex; align-items:center; justify-content:center; color:var(--muted);">Non d\u00e9finie</div>\n'
    '      </div>\n'
    '      {% endif %}\n'
    '    </div>\n'
    '  {% else %}\n'
    '    <p><em>Aucun fichier associ\u00e9 pour l\u2019instant.</em></p>\n'
    '  {% endif %}\n'
)

# Remplacer les lignes 317-400 (index 316 à 399 inclus)
lines[316:400] = [new_block]

with open('templates/show_form_edit.html', 'w', encoding='utf-8') as f:
    f.writelines(lines)

print('OK - bloc photos remplace')
